### ISSUE TITLE
Create Manager from connection string or existing tiberius config

### ISSUE THREAD

**Issue by russellbanks** [Geo-W/deadpool-tiberius#2]
In Tiberius, you can create a config from a connection string:

```rust
Config::from_ado_string(&CONN_STR);
Config::from_jdbc_string(&CONN_STR);
```

It would be useful if a Manager could be created from a connection string:
```rust
deadpool_tiberius::Manager::from_ado_string(&CONN_STR);
deadpool_tiberius::Manager::from_jdbc_string(&CONN_STR);
```
or from an existing tiberius config:
```rust
deadpool_tiberius::Manager::from(tiberius_config);
```

**Comment by Geo-W** [comment]
Thanks for your suggestion, fn added by #3 and will be available in `0.1.4` ~~
