### ISSUE TITLE
rustls support for tiberius

### ISSUE THREAD

**Issue by akffopr** [Geo-W/deadpool-tiberius#4]
Hi @Geo-W ,
  The tiberius can use rustls by disable "default-features" and enable "rustls". But Cargo.toml doesn't set default-features=false for tiberius. Can you fix it?, please~~

**Comment by Geo-W** [comment]
Hello @akffopr 
Thanks for pointing out!
In #5 Default feature is made optional and some of the features from `tiberius` is included. Is these features sufficient?
